export const MICRO_POLLS_MAINNET_CONTRACT_ADDRESS = 'SP2V3QE7H5D09N108CJ4QPS281Z3XAZVD87R8FJ27';
export const MICRO_POLLS_CONTRACT_NAME = 'micro-polls';
export const MICRO_POLLS_MAINNET_CONTRACT_ID = `${MICRO_POLLS_MAINNET_CONTRACT_ADDRESS}.${MICRO_POLLS_CONTRACT_NAME}`;
